camunda/camunda-bpm-assert

camunda-bpm-assert/src/main/java/org/camunda/bpm/engine/test/assertions/TaskAssert.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/TaskAssertHasFormKeyTest.java, camunda-bpm-assert/src/test/resources/TaskAssert-hasFormKey.bpmn, pom.xml
I changed camunda version to 7.2.0 to be able to implement this.
=> Fixed issue #39, by adding form key assert.

CONTRIBUTING.md
Worked on contribution guide. Wrote down everything I could recreate from mail exchanges.
=> 59 guidelines for contributing

camunda-bpm-assert/Coverage_CMMN.md, camunda-bpm-assert/User_Guide_CMMN.md, camunda-bpm-assert/src/main/java/org/camunda/bpm/engine/test/assertions/cmmn/AbstractCaseAssert.java, camunda-bpm-assert/src/main/java/org/camunda/bpm/engine/test/assertions/cmmn/HumanTaskAssert.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/HumanTaskAssertIsActiveTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/HumanTaskAssertIsAvailableTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/HumanTaskAssertIsCompletedTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/HumanTaskAssertIsDisabledTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/HumanTaskAssertIsEnabledTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/HumanTaskAssertIsTerminatedTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/HumanTaskAssertVariablesTest.java, camunda-bpm-assert/src/test/resources/cmmn/HumanTaskAssert-variables.cmmn, camunda-bpm-assert/src/test/resources/cmmn/HumanTaskAssertIsActiveTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/HumanTaskAssertIsAvailableTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/HumanTaskAssertIsCompletedTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/HumanTaskAssertIsDisabledTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/HumanTaskAssertIsEnabledTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/HumanTaskAssertIsTerminatedTest.cmmn
Added test cases and documentation for HumanTaskAsserts.
Also, variables(), hasVariables(), hasNoVariables() assertions are added for HumanTaskAssert - making them available for other types of case assertions should be done in a new issue (including tests and documentation).
=> 67 human task assert

.editorconfig, camunda-bpm-assert/Coverage_CMMN.md, camunda-bpm-assert/User_Guide_CMMN.md, camunda-bpm-assert/src/main/java/org/camunda/bpm/engine/test/assertions/cmmn/MilestoneAssert.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/MilestoneAssertIsAvailableTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/MilestoneAssertIsCompletedTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/MilestoneAssertIsTerminatedTest.java, camunda-bpm-assert/src/test/resources/cmmn/MilestoneAssertIsAvailableTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/MilestoneAssertIsCompletedTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/MilestoneAssertIsTerminatedTest.cmmn
=> PR for #70 MilestoneAssert

camunda-bpm-assert/Coverage_CMMN.md, camunda-bpm-assert/User_Guide_CMMN.md, camunda-bpm-assert/src/main/java/org/camunda/bpm/engine/test/assertions/cmmn/CaseTaskAssert.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/CaseTaskAssertIsActiveTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/CaseTaskAssertIsAvailableTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/CaseTaskAssertIsCompletedTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/CaseTaskAssertIsDisabledTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/CaseTaskAssertIsEnabledTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/CaseTaskAssertIsTerminatedTest.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/CaseTaskAssertVariablesTest.java, camunda-bpm-assert/src/test/resources/cmmn/CaseTaskAssert-variables.cmmn, camunda-bpm-assert/src/test/resources/cmmn/CaseTaskAssertIsActiveTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/CaseTaskAssertIsAvailableTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/CaseTaskAssertIsCompletedTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/CaseTaskAssertIsDisabledTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/CaseTaskAssertIsEnabledTest.cmmn, camunda-bpm-assert/src/test/resources/cmmn/CaseTaskAssertIsTerminatedTest.cmmn
=> PR for #76 CaseTaskAssert

camunda-bpm-assert/Coverage_CMMN.md, camunda-bpm-assert/User_Guide_CMMN.md, camunda-bpm-assert/src/main/java/org/camunda/bpm/engine/test/assertions/cmmn/CmmnAwareTests.java, camunda-bpm-assert/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/CmmnAwareTestsTest.java
Knowing that discussion about the feature has not started yet, here the pull request how I would add the feature.
=> PR for #84 complete case execution with variables

README.md
=> docs(readme): adjust credits

core/src/main/java/org/camunda/bpm/engine/test/assertions/bpmn/BpmnAwareTests.java
This change will ease the test of decision tables and diagrams
=> add helper method to access decision service

examples/bpmn/pom.xml, examples/cmmn/pom.xml, examples/pom.xml
[![](https://badgen.net/badge/JIRA//0052CC)](https://app.camunda.com/jira/browse/)
=> chore(examples): bump assert root version

pom.xml
[![CAM-11105](https://badgen.net/badge/JIRA/CAM-11105/0052CC)](https://app.camunda.com/jira/browse/CAM-11105)
=> CAM-11105: chore(project): bump relase parent

.travis.yml
[![CAM-11199](https://badgen.net/badge/JIRA/CAM-11199/0052CC)](https://app.camunda.com/jira/browse/CAM-11199)
so the travis build will fail on community contribution if the license headers are missing/broken
=> CAM-11199: chore(travis): add license check

pom.xml
=> chore(project): bump assertj to 3.16.1

.travis.yml, README.md, docs/User_Guide_BPMN.md, docs/User_Guide_CMMN.md, examples/bpmn/pom.xml, examples/cmmn/pom.xml, examples/pom.xml, pom.xml
=> chore(release): adjust for 8.0.0

examples/bpmn/pom.xml, examples/cmmn/pom.xml, examples/pom.xml
* bumps versions of examples' parent to 9.0.0-SNAPSHOT
=> bump internal versions

README.md, core/src/main/java/org/camunda/bpm/engine/test/assertions/bpmn/ProcessInstanceAssert.java, core/src/test/java/org/camunda/bpm/engine/test/assertions/bpmn/ProcessInstanceAssertHasBusinessKeyTest.java, core/src/test/resources/bpmn/ProcessInstanceAssert-hasBusinessKey.bpmn, docs/User_Guide_BPMN.md
- implements hasBusinessKey process instance assertion
- adds documentation on hasBusinessKey process instance assertion
related to CAM-10027
=> [CAM-10027] feat(assert): Add hasBusinessKey assertion

pom.xml
=> chore(pom): bump AssertJ to 3.18.1

README.md, core/src/main/java/org/camunda/bpm/engine/test/assertions/ProcessEngineTests.java, core/src/main/java/org/camunda/bpm/engine/test/assertions/bpmn/BpmnAwareTests.java, core/src/main/java/org/camunda/bpm/engine/test/assertions/bpmn/TaskAssert.java, docs/README.md, docs/User_Guide_BPMN.md, docs/User_Guide_CMMN.md
=> chore(repo): rename Camunda BPM Platform to Camunda Platform

.travis.yml, README.md, examples/bpmn/pom.xml, examples/cmmn/pom.xml, examples/pom.xml, pom.xml
=> chore(release): adjust for 10.0.0

pom.xml
- it is not used
related to CAM-13649
=> CAM-13649: remove Guava dependency

pom.xml
=> chore(deps): bump assertj to 3.20.2

README.md, examples/bpmn/pom.xml, examples/cmmn/pom.xml, examples/pom.xml, pom.xml
=> chore(release): adjust versions for 11.0.0

.ci.cambpm, core/src/test/java/org/camunda/bpm/engine/test/assertions/bpmn/ProcessEngineTestsTest.java, core/src/test/java/org/camunda/bpm/engine/test/assertions/cmmn/CmmnAwareTestsTest.java, examples/bpmn/src/test/java/org/camunda/bpm/engine/test/assertions/examples/JobAnnouncementPublicationProcessTest.java, pom.xml
- remove powermock
- update mockito to latest version & add mockito-inline for static tests
- fix ProcessEngineTestsTest & CmmnAwareTestsTest
- add jdk17 CI target
related to CAM-14399
=> chore(project): jdk17 support
